### ISSUE TITLE
No space between prefix and "help" in help command

### ISSUE THREAD

**Issue by DB8888** [ravendiscord/raven#3]
![image](https://user-images.githubusercontent.com/67452089/97626578-f31dee00-1a21-11eb-91d4-74dc86b1d92f.png)
There should be a space between "raven" and "help" :P

**Comment by ThaddeusKKR** [comment]
I plan to change the global prefix to something else, `raven` is only temporary. I can't put a space there because prefixes which don't intend to have a space in them would be affected, such as `raven!` or just `!`. 
With the new prefix system, the help command now shows the server prefix in the part you are showing.

**Comment by ThaddeusKKR** [comment]
The global prefix will be changed in the next major release.
